env:
  browser: true
  es2021: true
extends:
- airbnb
- plugin:react/recommended
- plugin:react-hooks/recommended
- plugin:import/typescript
- plugin:@typescript-eslint/recommended
- plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  import/extensions: 0
  import/prefer-default-export: "off"
  react/prop-types: 0
  no-console: 0
  prettier/prettier: "error"
  react-hooks/rules-of-hooks: "error"
  react/require-default-props: 0
  react/jsx-filename-extension: [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-props-no-spreading: "off"
  react/react-in-jsx-scope: 0
  import/no-extraneous-dependencies: ["error", {"devDependencies": ["**/*.test.tsx", "**/*.spec.ts"]}]
  "@typescript-eslint/no-empty-function": "off"
  no-empty-function": "off"
  import/no-unresolved: 0
  no-param-reassign: 0
  no-return-assign: 0
